### ISSUE TITLE
Express / Electron Lifecycle flaw

### ISSUE THREAD

**Issue by frankhale** [frankhale/electron-with-express#1]
The way it is currently working the Express server start up spawns Electron. While this works it's not ideal in my opinion for the following reason. Electron has no way to stop the Express server if Electron is closed. Instead we should fire up Electron and then spawn Express internally. This way when Electron is closed we can stop the Express server at the appropriate time.

I already have a working implementation of this and will upload it next week.

**Comment by Jonovono** [comment]
@frankhale have you uploaded that anywhere? would be interested in taking a look. thanks

**Comment by frankhale** [comment]
Yes I will be uploading this very likely tomorrow. I will reply back here when I do.

**Comment by frankhale** [comment]
@Jonovono, the code was just posted.

Closed via e50c752f1682d6d9092ad8a7e542fe8fdb9e5320

**Comment by frankhale** [comment]
If you have any ideas on how to improve this please let me know.

**Comment by frankhale** [comment]
A larger example here: https://github.com/frankhale/toby
