### ISSUE TITLE
Steps to run on OSX

### ISSUE THREAD

**Issue by xBau** [frankhale/electron-with-express#10]
The following steps worked for me:

- Download node binaries for OSX and extract the file.
- Copy the file called "node" into the root folder. There is no need of any other file (node.lib)
- In **index.html** change the line
```
node = spawn(".\\node", ["./express-app/bin/www"], {
```
to
```
node = spawn("./node", ["./express-app/bin/www"], {
```
- In **package.json** change the line
```
"start": ".\\node start-electron.js"
```
to
```
"start": "./node start-electron.js"
```

**Comment by frankhale** [comment]
Thanks for the information. I'll add it to the README soon!

**Comment by frankhale** [comment]
I've added your instructions to the README. Thank you!!!

**Comment by xBau** [comment]
Glad to have been helpful :)

**Comment by prayagupd** [comment]
not sure if its related to nodejs or not but, my app shows a wheel spinning.

env
----

```
$ node --version
v9.3.0

$ npm --version
5.6.0
```

**Comment by frankhale** [comment]
Press the F1 key to see the server log while the spinner is spinning to see if there is any useful error message. Basically what is happening is that the server is not completing it's start up so when the code polls to see if the express app is available it's failing so always spinning.

**Comment by xBau** [comment]
I would say that your issue could be related to that line in your package.json:
```
"start": "node start-electron.js"
```
Maybe with the previous line I think you are calling to your global node instance instead of your local copy? Try this instead:
```
"start": "./node start-electron.js"
```
