### ISSUE TITLE
Can you change the license to MIT?

### ISSUE THREAD

**Issue by dotku** [frankhale/electron-with-express#13]
I would like to contribute some work if the license is MIT. GNU need a lot of extra work

**Comment by frankhale** [comment]
I'm not opposed to switching to the MIT license but I would like to try to understand why the license would need to be changed before you would contribute work to this project. What specific things in the GNU GPL do you not like?

**Comment by frankhale** [comment]
Since there has been no response to my follow up question I'm going to close this for now. I am not opposed to changing the license but would like some decent arguments posed as to why the current GNU license is a bad choice.

**Comment by frankhale** [comment]
I've changed the license has been changed to MIT.
