### ISSUE TITLE
Support both win32 and win64

### ISSUE THREAD

**Issue by atlantiumtech** [frankhale/electron-with-express#19]
I'm trying to create installers for both `win32` and `win64`.
Which copy of `node.exe` should I copy? (32/64).

And how running `npm install` should be related to `node` version? (lets say my machine is `win64` and I want to create installer which can be use be `win32`)

What is the best approach to treat this use case?

**Comment by frankhale** [comment]
I don't typically build installers, I just zip up the files I need and distribute it that way. I'm not sure there is much need to differentiate between a 32 bit and 64 bit build unless you are getting some specific benefits from it. I just run the x64 build on all the machines I have access to. 

> What is the best approach to treat this use case?

I have no idea really what is being used to make installers these days. I think there is Electron Builder and Electron Packager but I haven't kept up with them to know which is the better approach.
