### ISSUE TITLE
No logging anymore

### ISSUE THREAD

**Issue by johman10** [frankhale/electron-with-express#2]
Hi there,

Thanks for this repo. It helped me out to get Express and Electron to work together.

You pushed a commit on the second of March (e50c752) which caused electron to not log anymore. It isn't showing page requests nor does it show `console.log()` and other debug functions in the terminal. Could you please help me out with why this is happening and how I can get these messages again?

Thanks in advance!

**Comment by johman10** [comment]
Maybe noteworthy: I can log from the `start-electron.js` file. But not from all the other files.

**Comment by frankhale** [comment]
I'll look into this.

**Comment by frankhale** [comment]
Yeah I can resolve this. I'll work on this later today when I get some free time. Thanks for reporting the issue!

**Comment by johman10** [comment]
Great! Thanks for your help in advance!

**Comment by frankhale** [comment]
I'll knock this out tomorrow.

**Comment by frankhale** [comment]
I have this done, will upload in just a few minutes.

**Comment by frankhale** [comment]
This is complete via 080c8e87d6ca644a45131b9710f51d78119c6550

**Comment by frankhale** [comment]
@johman10 this okay?

**Comment by johman10** [comment]
Hi there!
Thanks for your new commit. I will have a look at it when I have time.
I will come back to this issue to confirm. ;)
