### ISSUE TITLE
Sending messages to main process from express-app process

### ISSUE THREAD

**Issue by orensharon** [frankhale/electron-with-express#20]
I followed your tutorial to use express server with electron application.
Is it possible to send message from `express-process` to `renderer-process` or/and `main-process`?

The problem I'm facing:
After electron-app started, there's a login screen, after successful authentication (username and password) cookie is created, then, for every API request I'm checking if cookie exists.

Tried to test it on the browser and everything is working well.
When I start the electron-app, it seems like the renderer and the main process doesn't know about the cookies.

I tried to pass the ipcRenderer object to the client code like this: https://stackoverflow.com/a/48506328/2274300 but it doesn't seems to work (`window is undefined`)

Electron version: 3.0.13
React version: 16.7.0

**Comment by frankhale** [comment]
I would probably use Socket.IO with JSON Web Tokens to talk between the two processes.

**Comment by atlantiumtech** [comment]
Is it possible to put the `express-app` inside invisible window and then use the `ipcrenderer`?

**Comment by orensharon** [comment]
Is it possible to put the `express-app` inside invisible window and then use the `ipcrenderer`?

**Comment by frankhale** [comment]
The scenario where you communicate from the renderer to your backend via IPC or websockets is a fully supported in Electron. I do this in all my Electron apps. I don't know exactly what you are trying to achieve but generally you don't need to deviate much from standard Socket.IO examples or even using the Electron IPC examples. They all work out of the box.

**Comment by frankhale** [comment]
When I get some time I will make an example of how to do IPC communication between the render process and the main process. This would be really useful to have!!!

**Comment by frankhale** [comment]
I'm rewriting this since this current example is showing it's age. I'll include IPC comms between the renderer and the backend.

**Comment by frankhale** [comment]
Closing this in favor of tracking this in #21
