### ISSUE TITLE
electron-with-express rewrite

### ISSUE THREAD

**Issue by frankhale** [frankhale/electron-with-express#21]
`electron-with-express` is getting a rewrite!!! The current code is showing it's age so things are going to change a bit and get much more modern. The current state of the rewrite is in the rewrite branch. There are some things that still need to be worked out but it's already working. I will need to take some time to update the README to make all the steps necessary to run this thing documented.

Here are the core things being used to modernize this code:

- TypeScript
- Next.js with custom Express Server
- Socket.IO 
  - An instance at the Express server so you can do things from your API level
  - An instance at the Electron main process so you can talk to that process if you need to
- Material-UI

Rough edges / Things that will be fixed:

- README doesn't have much info yet =(
- Getting started. Cloning the repository and running this. There are some steps that need to be documented to make this easy.
- Processes exiting cleanly when the app exits. Currently I am working pretty hard to figure this one out because this is vital in my opinion. Nobody wants to use an app that starts a bunch of processes and then leaves them hanging around when the app is quit. It's super annoying and something I really want to solve as quickly as possible.

**Comment by frankhale** [comment]
The following issues will be resolved by this rewrite: #15, #20

**Comment by frankhale** [comment]
As mentioned above one of the goals of the rewrite is to figure out how to properly account for spawned processes such that they will exit cleanly when closing the app or when we can reasonably determine that something went wrong.

**Comment by frankhale** [comment]
Referencing issue Referencing issue https://github.com/frankhale/electron-with-express/issues/22

**Comment by IrosTheBeggar** [comment]
@frankhale I followed this project a while ago when I was looking into combing electron + express for my own project.  I already solved a lot of the problems you mentioned here, like adding a material UI and handling spawned processes.

[You can see my project here.](https://github.com/IrosTheBeggar/mStream) Thanks for the inspiration

**Comment by frankhale** [comment]
@IrosTheBeggar That's awesome!!! I will definitely take a look. Thank you for sharing that with me.

**Comment by EdmarPereira** [comment]
I don't know if somebody did this test, but I have problem to run this app with electron-builder, is there anybody else with the same problem ?

**Comment by frankhale** [comment]
technically electron-builder, package, etc... were always beyond the scope of this project because I just never packaged my apps like that so was not that interested in making it work. Additionally I did something here that probably nobody really would do in their app. I bundle the node executable along side Electron so that I can start the server outside of the Electron process. To get the bundlers and packagers to work you simply use start the server using Electron running as a traditional Node process. Pretty sure this would fix the issues.

**Comment by EdmarPereira** [comment]
Thank you very much for the feedback, and the problem was really the one that you explained. My packages related to the back-end were out of the src folder, when I generated the executable, Electron did not see those folders.

**Comment by frankhale** [comment]
This rewrite still may happen. I wanted to switch to Next.js. I'll reevaluate this soon.

**Comment by EdmarPereira** [comment]
You are correct but I fund a way for this problem. To start you need to include the backend folder in the  include  option inside package.json, doing this electron uses nodejs as base you juat need to create a module exports to start the express server and than require it on your electron starter (manin.js). Once you require it will start the express server
