### ISSUE TITLE
Express process is not killed if app closes before window has created

### ISSUE THREAD

**Issue by orensharon** [frankhale/electron-with-express#22]
After starting electron app, In case:
Express process has spawned, Browser-window hasn't created yet and app has closed (signal or error) then
node-express process is not been killed (I can see the 'dangling' node process in Task-Manager)

This is how I'm starting the express process (not detached):

    serverProcess = spawn(nodeDotExe, args, {
        cwd: app.getAppPath(),
        shell: true,
        env: process.env,
        windowsHide: true
    })

Killing the app (just like the rewrite):

    app.on("window-all-closed", function () {
        console.log('window-all-closed')
        if (process.platform !== "darwin") {
            app.quit();
        }
    });

Catching process events (exit, SIGINT, SIGUSR1, SIGUSR2) didn't help.

**Comment by frankhale** [comment]
Referencing issue https://github.com/frankhale/electron-with-express/issues/15 as well

**Comment by frankhale** [comment]
Processes exiting cleanly is being addressed in the rewrite branch. I'm going to close this as a duplicate and in favor of the issue that tracks the rewrite: https://github.com/frankhale/electron-with-express/issues/21

Additionally the process issue has been really tricky to figure out and is currently my biggest headache. If you have ideas on how to resolve this I am all ears. All future updates to this issue will happen in the issue that tracks the rewrite branch which I've mentioned above.

**Comment by orensharon** [comment]
I did some checks.
Tried to put `redirectOutput(..)` in comment and the child process killed.
It might be `ChildProcess.stdio` related issue.

According this thread https://stackoverflow.com/questions/32705857/cant-kill-child-process-on-windows :

`... the stdio stream of the parent process is still shared with the other processes in the tree. So the parent process is waiting for the stream to be closed`.

I will continue my tests.

**Comment by orensharon** [comment]
**Update:**
I discovered that when `shell: true`, the child process is wrapped by a new `Windows Command Processor` (you can see it in task-manager). 
For some reason, the `kill()` in `main.js` causes the child to detach (instead of to be killed) from the wrapper process.

I read about `fork`, it seems more correct interface for the current use case:
> The child_process.fork() method is a special case of child_process.spawn() used specifically to spawn new Node.js processes.

Now my code looks like this:

    const nodeDotExe = `${config.nodeExecPath}\\node.exe`
    const args = ['electron']

    serverProcess = fork("./express-app/index.js", args, {
        cwd: app.getAppPath(),
        execPath: nodeDotExe,
        stdio: 'pipe',
        env: {
            RESOURCES_PATH: config.resourcesFolder,
            USER_DATA: config.userData,
            SERVER_PORT: expressAppConfig.port
        }
    })
I hope I didn't miss anything, but now it seems that the problem is gone.

**Comment by frankhale** [comment]
Thanks @orensharon for your investigative work. In my rewrite branch I've had good success with how I'm doing it now. The process is dying nicely when I exit Electron (on Windows). Additionally I'm stood up some socket.io connections for communicating with server and electron main process. There is still some work to do but it's going nicely so far.

**Comment by orensharon** [comment]
I hope your solution won't be overkill..
Did you see what I wrote about `fork`? it's very simple solution ...

**Comment by frankhale** [comment]
I’m just using spawn and a module to kill process tree on electron close

**Comment by frankhale** [comment]
I see your code using fork. I will take a deeper look at it. Thank you for sharing this!!!!
