### ISSUE TITLE
electron-packager build not starting express server.

### ISSUE THREAD

**Issue by adrianlstein** [frankhale/electron-with-express#29]
**Describe the bug**
When running the application normaly from the command line everything works fine.

Once you make the changes to fit either the normal packaging or the ASAR packaging you will run into problems. After a bit of debugging I found out that the express server is not being started. I came to that conclusion because you can't access the usual routes through a normal webbrowser. 

**To Reproduce**
1. Pull the Code from the master branch
2. Adjust the node and app variables based on the information in the readme
3. Install electron-packager globaly or as dev dependency
4. Run the build Script found in the readme (remove the asar flag if you adjusted your set up for a non asar build)
5. Start the newly build application as admin or non admin user
6. The Screen will be stuck on "Loading..." and the Command line is not accessible

**Expected behavior**
The Backend Server Should start. Allowing the frontend to get the routes from it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by frankhale** [comment]
Thanks for reporting. I'll take a look.

**Comment by frankhale** [comment]
@adrianlstein with your PR merged I'm assuming we can close this one?

**Comment by adrianlstein** [comment]
@frankhale yes!
