### ISSUE TITLE
After create exe jquery module not found is showin

### ISSUE THREAD

**Issue by MonikaGodara127** [frankhale/electron-with-express#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]:-Windows

**Additional context**
Everything working fine in vscode after crate exe node server is not started and Jquery not found.Please help
![exe](https://user-images.githubusercontent.com/77720163/108677421-a8b00800-750f-11eb-84f7-614e88fbd6f8.PNG)

**Comment by frankhale** [comment]
Thanks for the bug report. I'll take a look.

**Comment by frankhale** [comment]
as @kkhanhm mentioned jQuery is no longer being used
