### ISSUE TITLE
if access the page from chrome, the express app will report error in log

### ISSUE THREAD

**Issue by dumpspecs** [frankhale/electron-with-express#33]
![Screenshot 2021-05-27 220806](https://user-images.githubusercontent.com/7556098/119823389-19fcbe00-bf38-11eb-8361-a46f4f7b1b2d.jpg)

**Comment by dumpspecs** [comment]
electron-with-express\express-app\views\include\head.ejs:3
1|
2|
>> 3|
4|
5|
title is not defined
at eval (electron-with-express\express-app\views\include\head.ejs:12:26)

**Comment by dumpspecs** [comment]
the url used in the chrome browser is:
http://localhost:3000/PageTwo

**Comment by frankhale** [comment]
Thanks for the bug report.

**Comment by frankhale** [comment]
This seems to be resolved now

![image](https://user-images.githubusercontent.com/190154/170832762-1bf3cee2-0796-4ed0-948b-3fe8a4d77f90.png)
