### ISSUE TITLE
require('electron').remote.app.getAppPath() no longer working

### ISSUE THREAD

**Issue by HaithamOumerzoug** [frankhale/electron-with-express#35]
app = require("electron").remote.app,
app.getAppPath() not working 
I got this error :
VM76 renderer_init.js:81 TypeError: Cannot read properties of undefined (reading 'app')

**Comment by dimaslanjaka** [comment]
use https://www.npmjs.com/package/@electron/remote

**Comment by frankhale** [comment]
Added `@electron/remote` to fix this
