### ISSUE TITLE
new version remote electron @electron/remote

### ISSUE THREAD

**Issue by dimaslanjaka** [frankhale/electron-with-express#43]
**Is your feature request related to a problem? Please describe.**
migrate to using https://www.npmjs.com/package/@electron/remote

**Describe the solution you'd like**
new electron remote using https://www.npmjs.com/package/@electron/remote

**Comment by frankhale** [comment]
Not really sure if there is much of a need for this since the only thing needed between the main process and the render process is the ability to shutdown gracefully. Currently that's being done with ipcRenderer. Is there a compelling reason to switch over to electron remote?

**Comment by frankhale** [comment]
Actually come to think of it I'm adding this now. Thanks for the suggestion.

**Comment by frankhale** [comment]
Added this, thank you!
