### ISSUE TITLE
add mongodb to the app

### ISSUE THREAD

**Issue by armanvirus** [frankhale/electron-with-express#49]
i think it will be much better to add mongodb to the app, so that the project will demonstrate how to create a fullstack app with electron, which has transportable embedder db within exe package.

**Comment by frankhale** [comment]
I've got a update that I haven't commited yet that uses `Sqlite`. I'm not sure I want to add `mongodb` to this repo. I may spin it off for more complex scenarios. The `Sqlite` update doesn't require spawning anymore process but `mongodb` would. I'm not opposed to it but I think it would be better suited for a more comprehensive example using a proper web framework like React, Vue or Angular as well to show off what can be done.

**Comment by armanvirus** [comment]
Ok, i got your point.
