### ISSUE TITLE
Only loading when I packaged using packager and run the exe file. it is not loading the ejs file.

### ISSUE THREAD

**Issue by iolathief108** [frankhale/electron-with-express#52]
Only loading when I packaged using packager and run the exe file. it is not loading the ejs file.

packager command: electron-packager . SmartPawnActivator --platform=win32 --arch=x64 --out=dist1 --asar --overwrite

and when I tried to get localhost:3000 it is not working.

**Comment by frankhale** [comment]
I just tested packing and everything is working on my end. Can you provide more info about your specific setup?

![image](https://github.com/frankhale/electron-with-express/assets/190154/24aebd52-788d-4ab7-857f-fc170375f644)

**Comment by iolathief108** [comment]
It worked with NPM, I don't think it works with Yarn

**Comment by frankhale** [comment]
@iolathief108 I just tried with Yarn and everything worked as expected for me. If you can provide some info about how it's working for you then maybe I can assist in fixing it.
