### ISSUE TITLE
can´t scroll logs

### ISSUE THREAD

**Issue by gentilmente** [frankhale/electron-with-express#7]
HI, awesome project.
Is there a way to see the latest logs?
When window is complete I don´t know what is happening

**Comment by frankhale** [comment]
Press F1 to see the server log. I also added overflow: auto to #serverLog CSS in index.html to allow for scrolling of the server log when its contents are larger than the main window.

**Comment by frankhale** [comment]
Closed via ee2264b8a43d1aeb9e091d8942e65a152d09bcf5

**Comment by frankhale** [comment]
Thanks for reporting this issue!!!
